<?php

namespace MyProject\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
	public function getListAll() {
		return $this->createQueryBuilder('p')
					->select('p.name,bt.name as bt_name,f.name as f_name')
					->from('MyProject\Entity\BlogType', 'bt')
					->from('MyProject\Entity\Field', 'f')
					->where('p.del_flg=0 AND p.blog_type_id = bt.id AND p.field_id = f.id')
					->getQuery()
					->getArrayResult();
	}
	
	public function getBlogById($id) {
		return $this->createQueryBuilder('p')
		->select('')
		->where('p.del_flg=0 AND p.id = :id')
		->setParameter('id',$id)
		->getQuery()
		->getSingleResult();
	}
}
