<?php

namespace MyProject\Repository;

/**
 * BlogTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllForCBB() {
		return $this->createQueryBuilder('bt')
			->select('bt.id, bt.name')
			->where('bt.del_flg=0')->getQuery()->getArrayResult();
	}
}
