<?php

namespace MyProject\Repository;

/**
 * BlogTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
