<?php

namespace MyProject\Repository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllForCBB() {
		return $this->createQueryBuilder('f')
		->select('f.id, f.name')
		->where('f.del_flg=0')->getQuery()->getArrayResult();
	}
}
