<?php

namespace MyProject\Repository;

use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends \Doctrine\ORM\EntityRepository implements \Symfony\Component\Security\Core\User\UserProviderInterface
{

	public function loadUserByUsername($username)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.user_id = :user_id')
            ->andWhere('c.del_flg = :delFlg')
            ->setParameters(array(
                'user_id' => $username,
                'delFlg' => 0,
            ))
            ->getQuery();
        $member = $query->getOneOrNullResult();
        if (!$member) {
            throw new UsernameNotFoundException(sprintf('Username "%s" does not exist.', $username));
        }

        return $member;
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        if (!$user instanceof \MyProject\Entity\Member) {
            return;
        }

        return $this->loadUserByUsername($user->getUsername());
    }

    public function supportsClass($class)
    {
        return $class === 'MyProject\Entity\Member';
    }
}
